"""initial migration.

Revision ID: 17427c6ed91e
Revises: 36362e6e8cf5
Create Date: 2021-10-21 05:01:34.127708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17427c6ed91e'
down_revision = '36362e6e8cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthdate', sa.String(length=10), nullable=True))
    op.drop_column('players', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthday', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('players', 'birthdate')
    # ### end Alembic commands ###
