"""empty message

Revision ID: 65a9d5f6f27e
Revises: 55407a326026
Create Date: 2021-10-24 07:39:39.782505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a9d5f6f27e'
down_revision = '55407a326026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'create_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    op.alter_column('comments', 'modify_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    op.alter_column('posts', 'create_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    op.alter_column('posts', 'modify_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'modify_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    op.alter_column('posts', 'create_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    op.alter_column('comments', 'modify_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    op.alter_column('comments', 'create_date',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    # ### end Alembic commands ###
